FROM ubuntu
RUN yum install -y java
VOLUME /Documentos/CursoSpring/tmp
ADD target/student.crud-0.0.1-SNAPSHOT.jar app.jar
RUN sh -c 'touch /app.jar'
EMTRYPOINT ["java","-Djava.security.egd=file:/dev/./undom","-jar","/app.jar"]
